let words: string[] = [
    'ARBOL', 'CASA', 'SOL', 'LUNA', 'GATO', 'PERRO', 'FLOR', 'PAN', 'AGUA', 'MESA',
    'SILLA', 'LIBRO', 'NUBE', 'PELOTA', 'RELOJ', 'ROPA', 'RATA', 'VASO', 'LEON', 'OSO',
    'PATO', 'RANA', 'MANO', 'PIE', 'OJO', 'BOCA', 'COLA', 'ROJO', 'AZUL', 'VERDE',
    'DADO', 'SAL', 'MAR', 'RIO', 'PAPEL', 'LUZ', 'FUEGO', 'HIELO', 'TREN', 'AUTO',
    'PUERTA', 'VENTANA', 'CAMINO', 'CAMISA', 'ZAPATO', 'SOMBRA', 'FRUTA', 'QUESO',
	'LAMPARA', 'VENTANA', 'MARIPOSA', 'ESPEJO', 'MONTANA', 'LIBRETA', 'TORMENTA',
    'SONRISA', 'NARANJA', 'PELUCHE', 'DRAGON', 'PINCEL', 'OCEANO', 'AVION', 'CUCHARA',
    'SILENCIO', 'BIBLIOTECA', 'FANTASMA', 'CHOCOLATE', 'PLANETA', 'JARDIN',
    'CARRETERA', 'ESTRELLA', 'SILLON', 'TELEFONO', 'PIRATA', 'CASTILLO', 'LLUVIA',
    'CUADERNO', 'SOMBRERO', 'BOSQUE', 'ISLA', 'TECLADO', 'VOLCAN', 'GALAXIA',
    'MONSTRUO', 'ALFOMBRA', 'DIAMANTE', 'GUITARRA', 'CALENDARIO', 'ESCALERA',
    'LINTERNA', 'DESIERTO', 'PELICULA', 'SEMAFORO', 'BICICLETA', 'LABERINTO',
	'ELECTRICIDAD', 'HELICOPTERO', 'REFRIGERADOR', 'MICROSCOPIO', 'ASTRONAUTA',
    'ROMPECABEZAS', 'NEBULOSA', 'SATELITE', 'TRAMPOLIN', 'MURCIELAGO',
    'TERMOMETRO', 'VENTILADOR', 'PINGUINO', 'PARAGUAS', 'AVELLANA',
    'COLIBRI', 'CARACOL', 'CASCADA', 'ESMERALDA', 'CUARZO',
    'ORQUESTA', 'ZANAHORIA', 'SERPIENTE', 'CANGURO', 'ANTENA',
    'PANTALLA', 'CALIDOSCOPIO', 'HORIZONTE', 'LABORATORIO', 'CONSTELACION',
    'EQUILIBRIO', 'FERROCARRIL', 'HIPOPOTAMO', 'ILUMINACION', 'JURASICO',
    'KILOMETRAJE', 'LUMINISCENCIA', 'MAGNETISMO', 'NAVEGACION', 'OBSERVATORIO',
    'PALEONTOLOGIA', 'QUIMICA', 'RESPIRACION', 'SISMOGRAFO', 'TELESCOPIO'
];
export function getRandonWord(){
    const randomIndex = Math.floor(Math.random() * words.length);
    return words[randomIndex];
}